# 공통
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.boot.autoconfigure: INFO

---
spring:
  config:
    activate:
      on-profile: logging-local

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.hibernate.type.descriptor.sql: TRACE
